export {default as Navbar} from './Navbar/Navbar'
export {default as NavigationFooter} from './NavigationFooter/NavigationFooter'
export {default as Loader} from './Loader/Loader'
export {default as Pagination} from './Pagination/Pagination'
export {default as SingleMovie} from './SingleMovie/SingleMovie'
export {default as Genre} from './Genre/Genre'